# Generated by Django 2.0.2 on 2018-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('usermail', models.CharField(max_length=300)),
                ('pass1', models.CharField(max_length=32)),
                ('pass2', models.CharField(max_length=32)),
                ('varsity', models.CharField(max_length=100)),
                ('experties', models.CharField(max_length=200)),
            ],
        ),
    ]
