# Generated by Django 2.0.2 on 2018-03-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationlist',
            old_name='experties',
            new_name='lovebooktype',
        ),
    ]
