# Generated by Django 2.0.2 on 2018-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0002_auto_20180304_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='userimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.CharField(max_length=300)),
                ('userimage', models.FileField(upload_to='')),
            ],
        ),
    ]
