# Generated by Django 2.0.2 on 2018-03-27 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
