# Generated by Django 2.0.2 on 2018-03-27 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0004_userimage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationlist',
            name='userimage',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
