# Generated by Django 2.0.2 on 2018-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0005_registrationlist_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicallpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.CharField(max_length=300)),
                ('booktitle', models.CharField(max_length=200)),
                ('bookwritter', models.CharField(max_length=200)),
                ('userphone', models.CharField(max_length=100)),
                ('usercomment', models.TextField(max_length=500)),
                ('usercontactinfo', models.TextField(max_length=400)),
                ('bookprice', models.CharField(max_length=20)),
                ('useroption', models.CharField(max_length=30)),
                ('bookimage', models.FileField(upload_to='')),
                ('bookview', models.IntegerField()),
            ],
        ),
    ]
