# Generated by Django 2.0.2 on 2018-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0006_publicallpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_personal_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.CharField(max_length=200)),
                ('postuniqid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registrationlist',
            name='usermail',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
