# Generated by Django 2.0.2 on 2018-03-28 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blovers', '0007_auto_20180329_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationlist',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
